services:
  - type: web
    name: stock-predict-backend
    env: python
    plan: free
    buildCommand: pip install -r Project/backend/requirements.txt
    startCommand: gunicorn wsgi:app
    workingDir: Project/backend
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.10

  - type: web
    name: stock-predict-frontend
    env: static
    staticPublishPath: Project/frontend
    buildCommand: ""
    pullRequestPreviewsEnabled: false
