services:
  - type: web
    name: stock-predict-backend
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn wsgi:app
    workingDir: .
    autoDeploy: true

  - type: web
    name: stock-predict-frontend
    env: static
    staticPublishPath: frontend
    buildCommand: ""
    pullRequestPreviewsEnabled: false
