services:
  - type: web
    name: stock-predict-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    workingDir: Project/backend
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.11

  - type: web
    name: stock-predict-frontend
    env: static
    staticPublishPath: Project/frontend/build
    buildCommand: npm install && npm run build
    autoDeploy: true
