services:
  - type: web
    name: stock-market-analysis
    env: python
    plan: free
    rootDir: ./Project/backend
    buildCommand: python -m pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:10000 app:app
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: GUNICORN_WORKERS
        value: 1
    preBuildCommand: apt-get update && apt-get install -y build-essential
    disks:
      - name: data
        mountPath: /opt/render/project/src/datasets
        sizeGB: 1
      - name: models
        mountPath: /opt/render/project/src/pretrained
        sizeGB: 1