services:
  - type: web
    name: stock-predict-backend
    env: python
    plan: free
    buildCommand: python -m pip install --upgrade pip && pip install -r Project/backend/requirements.txt
    startCommand: gunicorn --chdir Project/backend app:app
    workingDir: Project/backend
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: GUNICORN_WORKERS
        value: 1
    preBuildCommand: apt-get update && apt-get install -y build-essential
    disks:
      - name: data
        mountPath: /opt/render/project/src/datasets
        sizeGB: 1
      - name: models
        mountPath: /opt/render/project/src/pretrained
        sizeGB: 1
  - type: web
    name: stock-predict-frontend
    env: static
    staticPublishPath: Project/frontend/build
    buildCommand: npm install && npm run build
    autoDeploy: true