services:
  - type: web
    name: stock-predict-backend
    env: python
    plan: free
    rootDir: ./Project/backend  # Optional: Run commands from backend directory
    buildCommand: python -m pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: GUNICORN_WORKERS
        value: 1
    preBuildCommand: apt-get update && apt-get install -y build-essential
    disks:
      - name: data
        mountPath: /opt/render/project/src/datasets
        sizeGB: 1
      - name: models
        mountPath: /opt/render/project/src/pretrained
        sizeGB: 1
  - type: web
    name: stock-predict-frontend
    env: static
    rootDir: ./Project/frontend  # Optional: Run commands from frontend directory
    staticPublishPath: .
    buildCommand: ""  # No build required for static site
    startCommand: static  # Render handles static serving automatically
    autoDeploy: true